#在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
#禁止方式如下：在application.properties配置文件中增加以下内容
eureka:
  client.register-with-eureka: false
  client.fetch-registry: false

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/erpdb?autoReconnect=true&useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456mn
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true